name: 'Publish Docker Image to GitHub Registry'
description: 'GitHub Action to publish Docker Images to GitHub Registry'
inputs:
  github-token:
    description: 'GitHub token to push Docker image to GitHub Packages'
  image-name:
    description: 'Docker Image name'
    required: true
  image-tag:
    description: 'Docker Image tag'
    default: latest
  extract-git-tag:
    description: 'Extract git-tag from repository'
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.image-name }}
    - ${{ inputs.image-tag }}
    - ${{ inputs.extract-git-tag }}
branding:
  icon: 'box'
  color: 'blue'
